### PR TITLE
Extension/use server data

### LINKED ISSUE #47: Fetch and use userData from server for the extension UI

### LINKED ISSUE #49: Start making UI for the extension
Clicking the button should tell you to login, then display your quota for the day.

Should also tell you if the current site is blacklisted?

### LINKED ISSUE #52: debounce POST requests from extension for adding to browse_times
1. Don't want to overload the server
2. Don't want to actually add very short times (i.e. when switching through tabs quickly, the user is not actually browsing those tabs and these should not be counted as "hits")

I think 5 seconds for the delay would be reasonable.

### LINKED ISSUE #53: fetch (and store?) userData for extension's background script
Will need to extract blacklist and quota (and user options) to handle logic of whether to replace elements or not.

### LINKED ISSUE #54: Allow users to add the current website they're browsing to their blacklist via the extension

### LINKED ISSUE #57: Fix db queries for when nothing is retrieved
A lot of db queries broke today because there were no records in db and they were returning null, which then were processed by dataProcessor which tries to call `.map` on null. The fix is to have those queries return an empty array instead of `null`.

The sum queries also need to return `{sum: 0}` instead of null when nothing is found.

I am currently fixing those.

### LINKED ISSUE #59: Error in Leaderboards query
Query is not returning accurate sum of all durations.

Need to change where query starts and possibly the route it joins the tables.
Need to look into nested queries.

(Find all users bad browsing history over the past week. Sum each individual's durations over the week. Group by each individual. Order by time.)

### LINKED ISSUE #60: userData.quota_today contains time objects that have varying keys (units)
Right now it's something like:
```
allotment: {
hours: 2
minutes: 10
},
used: {
minutes: 12
},
all_browse_time: {
hours: 1
minutes: 12
}
```

The keys can vary based on the exact quantity of time. This needs to be converted so they only have a single unit key (i.e. `minutes:`)

### PR DESCRIPTION
**Pull request by jpqy**
Closes #47 
Closes #49 
Closes #53 
Closes #54 
Closes #57 

@xynyx @riztaha The extension loading has been changed:
1. Go to /chrome-extension-react
2. Run `npm run build`
3. Wait for it to finish and the `/build` folder to be created
4. `Load unpacked` in extensions using the `/build` folder

Further: 
Closes #52 
Fixes #59 
Fixes #60

### CODE REVIEW

**Review by riztaha — COMMENTED** [review]
Reviewed and approved changes in server/ files.

Still need to test extension.

**Comment by jpqy** [comment]
Closes #52

**Comment by jpqy** [comment]
Fixed #60

**Review by xynyx — APPROVED** [review]
Nice work. Times are being added to the db and cut off when I switch tabs.

The current browsing time is displayed as NaN right now though, and the time spent browsing in minutes should eventually be an integer.

When I add a domain to a blacklist using the button, it doesn't actually work until I navigate away from the page and back (refreshing it doesn't seem to work either).

I'd like to move as much state that isn't a controller component to useApplicationData at some point, but that isn't necessary right now.

The state doesn't seem to be refreshing/updating without closing and opening the extension window

**Comment by xynyx** [comment]
After your fix, the seconds is now displaying correctly (and updating in real time). Today's quota usage still not updating however.

**Comment by jpqy** [comment]
> The current browsing time is displayed as NaN right now though, and the time spent browsing in minutes should eventually be an integer.
>
Should be fixed now, timer value was being pulled from storage.sync when everything had been switched to storage.local.
 
> When I add a domain to a blacklist using the button, it doesn't actually work until I navigate away from the page and back (refreshing it doesn't seem to work either).
>
Yep right now only refreshing the background "page" works to reload the blacklist, will address as issue #61 .

**Comment by jpqy** [comment]
> After your fix, the seconds is now displaying correctly (and updating in real time). Today's quota usage still not updating however.

Today's used quota is fetched once from server as the UI is opened... not sure if it's useful to have it increase as the user stares at the popup for over a minute but I guess I can put that in. Also it can't really update because browse time is only added once user navigates away from tab, but I guess we can talk about if that's the best implementation (since right now the user can have 30 minutes left, and just be on reddit for an hour without navigating away and nothing would happen). So for now I'd have to hard-code a timer in just like with the "currently browsing" timer.

**Comment by xynyx** [comment]
> > After your fix, the seconds is now displaying correctly (and updating in real time). Today's quota usage still not updating however.
> 
> Today's used quota is fetched once from server as the UI is opened... not sure if it's useful to have it increase as the user stares at the popup for over a minute but I guess I can put that in. Also it can't really update because browse time is only added once user navigates away from tab, but I guess we can talk about if that's the best implementation (since right now the user can have 30 minutes left, and just be on reddit for an hour without navigating away and nothing would happen). So for now I'd have to hard-code a timer in just like with the "currently browsing" timer.

Yeah it's honestly not necessary and probably not worth spending time on. I think the next goal is to mess with the text.

**Comment by riztaha** [comment]
Reviewing extension:

browse_times added to db upon switching tabs.
data adjusting in charts accordingly.

domain added to blacklist in db upon clicking button.

Bug - Images changing before quota is reached.

**Pull request merged**
