### PR TITLE
Client/add chart titles

### LINKED ISSUE #68: Add titles to elements

### PR DESCRIPTION
**Pull request by xynyx**
Happy with how this is looking now. Can add a backdrop later so it's not all white and do other tweaks.

### CODE REVIEW

**Comment by riztaha** [comment]
Much improved UI from before! Looks really good!

Note for Demoday: 
Charts look best on 13" 1280*800px at 75%
at 100% it looks like gif attached, then I change it to 75%.

https://imgur.com/a/bQ7Qa0z

**Review by riztaha — APPROVED** [review]

**Comment by xynyx** [comment]
I haven't touched the spacing on the smaller screen at all but it should be
easy enough later on to do media queries.

I think my current media cutoff is too high for ppl with lower resolutions.
Change the media queries to a lower res and you'll see what it's supposed
to look like

**Review by xynyx — COMMENTED** [review]
I think the line graph is a little too far down now, and the spacing on the final graph is a little much at the bottom, but solid otherwise.

**Review by jpqy — APPROVED** [review]
I shifted some elements around a bit but definitely room for more tweaking. Each card does seem to show differently based on people's resolution so keep that in mind when discussing how something looks.

**Pull request merged**
