### PR TITLE
Extension/auto gradual replacement

### LINKED ISSUE #8: After visiting a certain domain, slowly and randomly replace images one by one
- Use setTimeOut somewhere in the function
- Need to check domain/host name of tab
- Need to trigger function on every page load

### LINKED ISSUE #22: Add support for video replacement

### LINKED ISSUE #23: Add support for replacement of new nodes when DOM is changed
Currently any newly loaded content (i.e. infinite scrolling) doesn't get replaced unless you switch tabs back and forth, due to when the script is injected.

### LINKED ISSUE #26: Ensure queued up actions to replace nodes are not overlapping
Need to do this as a result of current implementation of #23 (use of setInterval to periodically call the element-replacement function)

### LINKED ISSUE #27: Listen for DOM changes with MutationObserver
Use a better method than the setInterval implementation in #23 to handle DOM changes caused by ajax (i.e. infinite scroll)

https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver

### LINKED ISSUE #33: Make sure script isn't called too much with MutationObserver

### PR DESCRIPTION
**Pull request by jpqy**
Closes #8 
Closes #22
Closes #23 
Closes #26 
Closes #27 
Closes #33

### CODE REVIEW

**Comment by riztaha** [comment]
- Reddit images are being changed.

- Youtube images are being changed upon index load.
Clicking a youtube video sometimes plays intended video instead of Rick Roll.

- Instagram images/videos change to meme, but upon double clicking an image (liking the post), it displays the intended image. Videos will not play (good!)

- Facebook images/videos changing, didn't find any issues.

If we can overcome these bugs next thing to work on would be changing text to gibberish.

**Comment by jpqy** [comment]
>   Clicking a youtube video sometimes plays intended video instead of Rick Roll.
> * Instagram images/videos change to meme, but upon double clicking an image (liking the post), it displays the intended image. Videos will not play (good!)

Good catch, I think I know the issue... I had made it so that upon changing the src of the img/video, I would add an attribute to the element so the script wouldn't change it again. That's why upon clicking "like" the image reverts... instagram is changing the src back to the original. I need to revert back to checking for src instead of inserting an attribute.

**Comment by xynyx** [comment]
Tested on multiple sites; seems to work really well. Images and videos are replaced properly with infinite scrolling, and the problem that riztaha described doesn't seem to be happening to me anymore.

Ready to merge

**Review by xynyx — APPROVED** [review]
Tested on multiple sites; seems to work really well. Images and videos are replaced properly with infinite scrolling, and the problem that riztaha described doesn't seem to be happening to me anymore.

Ready to merge

**Pull request merged**
