### PR TITLE
Server/intial routing

### LINKED ISSUE #24: Setup some routing to get user data across

### PR DESCRIPTION
**Pull request by riztaha**
Still need to change routes for /blacklists & /add_browse_time to work with userId properly.

/user/data working properly based off user who has logged in.

### CODE REVIEW

**Review by jpqy — CHANGES_REQUESTED** [review]
Add this logic in all of the routes in userRoutes: 
1. Store the req.session.userId in a const userId so you don't have to type it every time. If userId is falsy, return res.status(404).send("error message") to cut off the route here. Do the opposite for /login and /register. This is the first thing that needs to be done for all the routes. 
2. If const userId is truthy, assume user exists and continue on with dbHelpers using const userId as the param.
3. The dbHelper chain for `GET /data` is faulty. Inside every `.then` you need to use the param to add to the data object, and end by returning another dbHelper call. Data is only returned at the very end. Message me for further clarification.

**Comment by xynyx** [comment]
For the add_browse_time and blacklists routes, your code is currently:

```
 let siteID;
    dbHelper
      .getWebsiteIDByHostname(host_name)
      .then((site) => (siteID = site.id))
      .then(dbHelper.addBrowseTimesToUserID(user_id, siteID, duration))
      .catch((err) => res.json(err));
```
You don't actually need to create an empty variable and then do `.then((site) => (siteID = site.id))`; in fact it will prevent the chain from continuing because it doesn't actually return anything. You already have the site returned from the previous promise, so you can just pass in site.id to the dbHelper:

```
    dbHelper
      .getWebsiteIDByHostname(host_name)
      .then((site) => {
       return dbHelper.addBrowseTimesToUserID(user_id, site.id, duration))
}
      .catch((err) => res.json(err));
```

**Review by xynyx — COMMENTED** [review]
Made some major changes to how the object data is structured - it now looks like this:

```
{
"user": {
"id": 1,
"first_name": "Aaron",
"last_name": "Aaronson",
"email": "a@a.com",
"password": "$2a$10$FB/BOAVhpuLvpOREQVmvmezD4ED/.JBIDRh70tGevYzYzQgFId2u.",
"options": null
},
"quota_today": {
"allotment": {
"hours": 3
},
"used": {
"hours": 1,
"minutes": 10
},
"all_browse_time": {
"hours": 3,
"minutes": 10
}
},
"radialGraph": [
{
"name": "Reddit",
"hits": 1
},
{
"name": "Twitter",
"hits": 5
}
],
"donutGraph": [
{
"website": "ESPN",
"time": 40
},
{
"website": "Facebook",
"time": 40
},
{
"website": "Other",
"time": 40
},
{
"website": "Reddit",
"time": 29
},
{
"website": "Twitter",
"time": 41
}
],
"lineGraph": [
{
"date": "2020-04-26T04:00:00.000Z",
"time": 200
},
{
"date": "2020-04-27T04:00:00.000Z",
"time": 120
},
{
"date": "2020-04-28T04:00:00.000Z",
"time": 20
},
{
"date": "2020-04-29T04:00:00.000Z",
"time": 50
},
{
"date": "2020-04-30T04:00:00.000Z",
"time": 90
},
{
"date": "2020-05-01T04:00:00.000Z",
"time": 300
},
{
"date": "2020-05-02T04:00:00.000Z",
"time": 49
},
{
"date": "2020-05-03T04:00:00.000Z",
"time": 19
},
{
"date": "2020-05-04T04:00:00.000Z",
"time": 92
},
{
"date": "2020-05-05T04:00:00.000Z",
"time": 18
},
{
"date": "2020-05-06T04:00:00.000Z",
"time": 24
},
{
"date": "2020-05-07T04:00:00.000Z",
"time": 39
},
{
"date": "2020-05-08T04:00:00.000Z",
"time": 90
},
{
"date": "2020-05-09T04:00:00.000Z",
"time": 100
},
{
"date": "2020-05-10T04:00:00.000Z",
"time": 41
},
{
"date": "2020-05-11T04:00:00.000Z",
"time": 64
},
{
"date": "2020-05-12T04:00:00.000Z",
"time": 70
}
],
"leaderboard": [
{
"name": "Aaron",
"time": 1974
},
{
"name": "Test",
"time": 340
},
{
"name": "Rachel",
"time": 300
},
{
"name": "Ross",
"time": 200
},
{
"name": "Monica",
"time": 164
},
{
"name": "Phoebe",
"time": 100
}
],
"shameboard": [
{
"name": "Chandler",
"time": 40
},
{
"name": "Joey",
"time": 64
},
{
"name": "Phoebe",
"time": 100
},
{
"name": "Monica",
"time": 164
},
{
"name": "Ross",
"time": 200
},
{
"name": "Rachel",
"time": 300
}
]
```
1) I created another query that groups the hits per blacklisted website for the radial chart, since the chart is based off hits and not time.

2) I grouped together daily quota values for the user under one object

You might want to refactor the createDonutData/Chart/Board functions into one function that takes in the specific graph parameter.

**Comment by xynyx** [comment]
Looks good - object is now in correct form for graphs to process.

**Review by jpqy — APPROVED** [review]

**Pull request merged**
