### PR TITLE
Quota bug conditional display

### LINKED ISSUE #78: Edge case - Quota graph over 100%
Currently, if the user goes over their cap, they will not see how much they've went over in the quota graph.

Implement similar approach to dynamic drawer msg to show how much % a user has gone over in the graph.

### LINKED ISSUE #86: General styling touch ups, fix fonts, create interesting logo, polishing

### LINKED ISSUE #103: Spacing issues with navbar menu items being too low

### PR DESCRIPTION
**Pull request by xynyx**
1) Fixed quota gauge bug
2) Conditional rendering on gauge that displays "You are 52% over quota!" if you go over 100%.
3) Made some significant styling changes to Navbar (much happier with it now!)
4) Increase subtitle sizes on dashboard page

### CODE REVIEW

**Comment by xynyx** [comment]
Replaced our logo as a button with a menu open icon. Kept the logo in the center but is no longer a button. Added a box shadow to the rainbow in the navbar. Not sure what else to do with it - can't really create a blur effect.

**Comment by riztaha** [comment]
Good work Matt! Glad we peer programmed (with you being the driver), got some good insight into React and helped solve some issues.

Gauge bug fixed.
Conditional rendering added for % over.
Navbar looks way nicer!!!
Subtitles should be readable for viewers on demo day now.

👍 👍 👍

**Review by riztaha — APPROVED** [review]

**Review by jpqy — APPROVED** [review]
Everything looks much better. Only thing I'd change (not for this PR but in the future) is the top of the drawer, right now it's a bit repetitive with the same image/icon shown on main page to the right. Good job guys!

**Comment by xynyx** [comment]
Made some final finishing touches. Noticed that the drawer looked different on the options page compared to dashboard - it was because a ThemeProvider was changing the font on the options page.

Going to merge.

**Pull request merged**
