### PR TITLE
Server/profile pic

### LINKED ISSUE #80: Add pictures to boards
Currently, users do not have pictures.

Add pictures to make available for leaderboards (later, allow users to edit/change their images).

### LINKED ISSUE #82: Bug when adding "www.espn.com
to reproduce: add "www.espn.com"
add "espn.com"
add "Espn.com"

Remember, this site already exists in db.

### PR DESCRIPTION
**Pull request by riztaha**
Created db/server capability to show images in boards.
images being sent in board userObject data to client.
Client amCharts picking up the images for each user.

Changed some seeds to make data look nicer for demo day.

### CODE REVIEW

**Comment by riztaha** [comment]
Closes #80

**Review by jpqy — APPROVED** [review]
Looks good to me, need to add at least 2 more seeds and probably remove GIFs later as they are kind of distracting.

**Review by xynyx — APPROVED** [review]
I like the smaller subtitles actually, looks nice!

**Comment by riztaha** [comment]
Bug fixed!!!!!!!
Please review again.

**Review by jpqy — APPROVED** [review]
Looked through the updated route `/blacklist/add`, logic is sound. Added further clarifying comments.

**Review by xynyx — APPROVED** [review]
Nicely fixed. Think this one's ready to merge.

**Comment by riztaha** [comment]
Finally fixed bug #82 
Needs to be refactored.
websiteScoped was returning null because it never existed for the user.

**Pull request merged**
