### PR TITLE
Server/database setup

### LINKED ISSUE #10: Creating Databases
On branch server/database-setup

### LINKED ISSUE #11: Creating Seeds

### PR DESCRIPTION
**Pull request by riztaha**
Need to go over some files together.

Schema/websites, should the hostname primary key be a text or an integer? I'm thinking it should be the website URL eg. 'www.reddit.com', ...

Schema/browse_times, making an assumption for 'duration' column.

Schema/quotas, read commented lines at bottom of file.

### CODE REVIEW

**Review by jpqy — CHANGES_REQUESTED** [review]
Schemas
1.  Let's just give websites a id primary key because hostname will have a period which can mess up the url. So change hostname to varchar(255) unique not null
2. Change table name blacklist to blacklists to be consistent with other tables
3. Change FK for website_id on blacklists, browse_times
4. Change all `timestamp without time zone` to `timestamp with time zone`
5. browse_time: duration should be type `INTERVAL`, set default as 1 minute. Making it a time format instead of integer makes it so much easier to work with when we eventually have to.
6. quotas: dates_valid should be type `DATE` because like other quotas i.e cell phones, they reset at midnight. date_valid_from default would be `CURRENT_DATE`, date_valid_until default would be ~~`TOMORROW`~~ actually make it `INFINITY`

Seeds:
Adjust accordingly to changed schemas
Hostnames should be xxxx.yyy (one period, no www)

**Review by xynyx — COMMENTED** [review]
Are we currently leaving the quota as just a number that they set? Should we adjust this so that it's based on a percentage of a daily period they set, or leave that for later?

For the quota seed, the interval would be a smaller number (like 2 hours or something), rather than the whole 24 hours, no?

Can I actually get some clarification on the interval and date start and end? Does the interval represent the time they want to be able to browse freely or the period of the day that they want sites blocked?

**Comment by jpqy** [comment]
> Are we currently leaving the quota as just a number that they set? Should we adjust this so that it's based on a percentage of a daily period they set, or leave that for later?

The schema setup for quotas and what the value of the quota should be for the user are two separate concerns.

> For the quota seed, the interval would be a smaller number (like 1 hour or something), rather than the whole 24 hours, no?

The 2 hour value you're talking about is the `interval` column in quota... actually it might be a bad column name since interval is a data type so let's change the column name to `allotment` with type `INTERVAL` (instead of `integer`). It doesn't have a default value for now, maybe 2 hours would be a good default.

**Comment by jpqy** [comment]
Forgot to add that the users table needs an `options` column of type `JSONB`

**Review by jpqy — CHANGES_REQUESTED** [review]
browse_times: website_id should be FK, not website_hostname

**Pull request merged**
