### PR TITLE
Server/queries setup

### LINKED ISSUE #13: Adding basic queries
Setup queries for: getBlacklistedWithUserID, getAllWebsites, addWebsite, addWebsiteToBlacklist, addQuotaForUser.

### PR DESCRIPTION
**Pull request by riztaha**
Basic setup of some initial queries we will need.

### CODE REVIEW

**Review by jpqy — CHANGES_REQUESTED** [review]
`getBlacklistedWithUserID` - websites table doesn't have user_id column, need to join to blacklists table
`addQuotaForUser` - start_date and end_date will have to be the parameters instead of interval, not sure where interval came from

Other things will need to be changed due to changes in schema.
Let's hold off on merging this until db has been seeded and we can run these test queries in psql to make sure they work.

**Comment by riztaha** [comment]
Please review so I can merge pull request. All queries have been tested and are working in the db.

**Review by jpqy — CHANGES_REQUESTED** [review]
1. All your insert queries should have RETURNING *; at the end to return the item it just inserted
2. addQuotaForUser needs to take parameters to set `date_valid_from` and `date_valid_until` and conditionally handle it when optional parameters are not passed in. This also applies to addBrowseTimesToUserID

**Review by xynyx — COMMENTED** [review]
Looks good.

I think we could use something like percentageOfDailyQuotaUsage and percentageOfLifetimeQuotaUsage, based off how much quota they used vs how much quota they had, just for the charts on the analytics page. We'll probably end up needing a few more interesting stat based queries for charts later.

**Comment by jpqy** [comment]
> I think we could use something like percentageOfDailyQuotaUsage and percentageOfLifetimeQuotaUsage

The first one, `percentageOfDailyQuotaUsage` might be worth doing since the chrome extension could use that to get a simple value for determining if the user is over quota and by how much, which it needs in order to decide whether and how aggressively to mess with the page. The second one is not very useful. For rendering the charts we would want the db to return a large bundle of raw, unprocessed data, not just the percentage since the percentage is just one number. We need a lot more than just the percentage to do our charts so it's best if one query returns a lot more raw data, which the client then processes to generate the charts.

**Review by jpqy — CHANGES_REQUESTED** [review]
So the quotas table has a bunch of rows representing different quotas set for different time periods for a single user.

1. Rename `getQuotaWithUserID` to `getAllQuotasWithUserID` and return `res.rows` not `res.rows[0]` (used eventually for graphs)
2. Make a `getQuotaForTodayWithUserID` query like the previous but returning `res.rows[0]` and includes where statements to get a single row where `current_timestamp` is between the 2 validity columns. This query will be needed for the extension as part of MVP.

**Review by jpqy — APPROVED** [review]
No more obvious mistakes I can spot for now. Going to merge so everyone can start using these queries in routes.

**Pull request merged**
