### PR TITLE
Client/analytics graphs

### LINKED ISSUE #31: Use AmCharts charting library to create charts

### LINKED ISSUE #32: Create final user object scaffold with fake data for analytics page

### LINKED ISSUE #38: Get charts to retrieve database data and render them
Currently charts are working with fake data

### PR DESCRIPTION
**Pull request by xynyx**
Analytics page (essentially) complete - database is fully hooked up.

Everything is mostly in place, but there's a few issues that I can't seem to figure out.

1) For big enough pieces in the donut, the top part gets clipped. Padding and margin not working as expected.

2) Would be nice to get the leaderboards just a little closer, and the pie/radial closer as well. Things not working as expected here either.

Besides some styling issues... milestone achieved!

### CODE REVIEW

**Review by xynyx — COMMENTED** [review]
Fixed spacing issues with help from riztaha. Graphs aren't clipping anymore. Looks purrty.

**Review by jpqy — APPROVED** [review]
A good milestone! Charts are updating (after refresh) as the user browses sites, can definitely implement websocket later so no need to refresh. Title/layout can be fixed later.

The `loading` state, as part of `useApplicationData`, is not set up correctly nor used, but current implementation of conditional rendering of `Dashboard` based on whether the dashboard data exists yet works fine for now. We can switch to using the `loading` state later so don't delete that code yet.

Some very minor edits that I would recommend:
1. Better variable name for the dashboard data prop. Naming it `dashboard` is pretty ambiguous since the Dashboard component has the same name but capitalized. I suggest renaming the `dashboard` prop something like `dashboardData` to be more explicit about what it's storing.

2. I don't recommend naming the "other" websites "Whitelisted" in our schema because that implies the user actually has a list of websites they can add to that are whitelisted. How about "Non-Blocked Sites"?

**Comment by xynyx** [comment]
The "loading" state was my first attempt, and while it does work (though it's not longer fully set up anymore), I found the conditional rendering to be a little nicer. With the loading state the loading spinner doesn't appear for very long and looks jarring, but with the conditional rendering it's a little longer. That actually may not be a good thing and is up to interpretation.

Will make those minor edits now and merge afterward.

Still to do: set up links/logout on navbar.

**Review by xynyx — COMMENTED** [review]
The "loading" state was my first attempt, and while it does work (though it's not longer fully set up anymore), I found the conditional rendering to be a little nicer. With the loading state the loading spinner doesn't appear for very long and looks jarring, but with the conditional rendering it's a little longer. That actually may not be a good thing and is up to interpretation.

Will make those minor edits now and merge afterward.

Still to do: set up links/logout on navbar.

**Pull request merged**
