### PR TITLE
Server/fix cookie policy

### PR DESCRIPTION
**Pull request by jpqy**
Tried to login today but couldn't so I did some exploring. Seems like Chrome updates affected our cross-site cookies: https://duo.com/decipher/google-rolls-out-samesite-cookie-changes-to-chrome

Spent some time looking into it... was close to just saying screw it and implementing JWTs, but figured it out eventually. It's already deployed to Heroku too... I had to test a bunch of times but it ended up being two lines of code 🤣

### CODE REVIEW

**Comment by xynyx** [comment]
Makes sense as to why you had to add `sameSite: none`, but why did you have to add `cookie: false` (I assume since you aren't using any cookies with socketIO?) & `secureProxy: true`?

**Review by xynyx — APPROVED** [review]

**Review by xynyx — COMMENTED** [review]
Makes sense as to why you had to add `sameSite: none`, but why did you have to add `cookie: false` (I assume since you aren't using any cookies with socketIO?) & `secureProxy: true`?

**Comment by jpqy** [comment]
> Makes sense as to why you had to add `sameSite: none`, but why did you have to add `cookie: false` (I assume since you aren't using any cookies with socketIO?) & `secureProxy: true`?

You can click on the ellipsis next to my commit messages above, I think it's all explained in the body. 

SocketIO didn't turn out to be the cause of the problem but its cookies were not being used and giving a console warning for the same reason our cookies were. 

`secureProxy: true` is a way to tell the `cookies` package that it's okay to set the cookies as `Secure`.

**Comment by xynyx** [comment]
> > Makes sense as to why you had to add `sameSite: none`, but why did you have to add `cookie: false` (I assume since you aren't using any cookies with socketIO?) & `secureProxy: true`?
> 
> You can click on the ellipsis next to my commit messages above, I think it's all explained in the body.
> 
> SocketIO didn't turn out to be the cause of the problem but its cookies were not being used and giving a console warning for the same reason our cookies were.
> 
> `secureProxy: true` is a way to tell the `cookies` package that it's okay to set the cookies as `Secure`.

Oh dang I just noticed that feature next to the commits. Nice. I guess that's like a separate commit message you can add that isn't a part of the original commit message? Gotta start using that.

**Pull request merged**
