### PR TITLE
Feature/register

### LINKED ISSUE #5: Create basic register form
Routes not created

### LINKED ISSUE #6: Create Logo & Text next to register form on landing page

### PR DESCRIPTION
**Pull request by xynyx**
Prelim landing page. Not set in stone.

Closes #5 
Closes #6

### CODE REVIEW

**Review by jpqy — COMMENTED** [review]
I will try changing landing page proportions between main and register box

**Comment by jpqy** [comment]
Before:

After tweaking things a bit:

**Comment by jpqy** [comment]
After removing tint (not sure if tint was intentional):

**Comment by riztaha** [comment]
Landing page looks really good!

Only suggestion is font color and background color clash.

Refer to: 
https://tinyurl.com/y7uncvqv
https://tinyurl.com/yasut8z5

**Comment by jpqy** [comment]
> Only suggestion is font color and background color clash.

I agree, text right now is a bit hard to read.

**Comment by xynyx** [comment]
Looks pretty good, but I still think it might look better if we do the 66-33 that we discussed and then have the rainbow portion blur/fade into the other part. Can experiment later.

**Comment by xynyx** [comment]
True about the text but white text with black border may not look that great, though it may be the only option. We could also add some sort of card/paper background behind the words but then you lose half the background

**Review by jpqy — COMMENTED** [review]
Yeah definitely gonna be tweaked in the future... I suggest we merge this for now just so we have something concrete on master to work with?

**Comment by xynyx** [comment]
Agreed. Ready to merge.

**Pull request merged**
